# Generated by Django 5.0 on 2023-12-15 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('useradmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='staffmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('im', models.ImageField(upload_to=None)),
                ('name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=50)),
                ('qualification', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('join_date', models.DateField()),
                ('till', models.DateField()),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useradmin.useradminmodel')),
            ],
        ),
    ]
