# Generated by Django 5.0 on 2023-12-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmodel',
            name='till',
            field=models.DateField(blank=True, null=True),
        ),
    ]
