# Generated by Django 5.0 on 2023-12-18 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_staffmodel_till'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmodel',
            name='im',
            field=models.ImageField(upload_to='staff'),
        ),
    ]
