# Generated by Django 5.0 on 2023-12-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_staffmodel_im'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='staffmodel',
            name='password',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
