# Generated by Django 5.0 on 2023-12-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_staffmodel_im'),
    ]

    operations = [
        
    ]
