# Generated by Django 5.0 on 2023-12-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_staffmodel_email_staffmodel_password'),
    ]

    operations = [
        
    ]
