# Generated by Django 5.0 on 2023-12-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_staffmodel_email_staffmodel_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmodel',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='staffmodel',
            name='password',
            field=models.CharField(max_length=254),
        ),
    ]
