# Generated by Django 5.0 on 2023-12-20 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_alter_staffmodel_email_alter_staffmodel_password'),
    ]

    operations = [
        
    ]
