# Generated by Django 5.0 on 2023-12-20 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_remove_staffmodel_email_remove_staffmodel_password'),
    ]

    operations = [
        
    ]
