# Generated by Django 5.0 on 2023-12-27 07:47

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('staff', '0007_alter_staffmodel_options'),
    ]

    operations = [
        
    ]
