# Generated by Django 5.0 on 2023-12-27 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_alter_staffmodel_managers_staffmodel_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffmodel',
            options={'default_related_name': 'staff_user'},
        ),
    ]
