# Generated by Django 5.0 on 2023-12-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_alter_staffmodel_options_alter_staffmodel_groups_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffmodel',
            options={'verbose_name': 'Staff', 'verbose_name_plural': 'Staff Members'},
        ),
        migrations.AddField(
            model_name='staffmodel',
            name='user_type',
            field=models.CharField(choices=[('Student', 'Student'), ('Staff', 'Staff')], default='Staff', max_length=20),
        ),
    ]
