# Generated by Django 5.0 on 2023-12-27 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_alter_staffmodel_options_staffmodel_user_type'),
    ]

    operations = [
    ]
