# Generated by Django 5.0 on 2023-12-27 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0013_remove_staffmodel_added_by'),
        ('useradmin', '0010_delete_roletype_alter_useradminmodel_options'),
    ]

    operations = [
       
    ]
