# Generated by Django 5.0 on 2023-12-28 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0015_remove_staffmodel_address_and_more'),
        ('useradmin', '0010_delete_roletype_alter_useradminmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmodel',
            name='added_by',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='useradmin.useradminmodel'),
        ),
    ]
