# Generated by Django 5.0 on 2023-12-15 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('im', models.ImageField(upload_to=None)),
                ('name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=50)),
                ('sclass', models.CharField(choices=[(1, 1), (2, 2), (3, 3)], max_length=50)),
                ('age', models.IntegerField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('Admitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staffmodel')),
            ],
        ),
    ]
