# Generated by Django 5.0 on 2023-12-18 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmodel',
            old_name='Admitted_by',
            new_name='admitted_by',
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='im',
            field=models.ImageField(upload_to='student'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='sclass',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=50),
        ),
    ]
