# Generated by Django 5.0 on 2023-12-19 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_examresultmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examsmodel',
            old_name='taken_by',
            new_name='studentforexam',
        ),
        migrations.RemoveField(
            model_name='examsmodel',
            name='subject_name',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='age',
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='DOB',
            field=models.DateField(default='2023-9-12'),
        ),
        migrations.CreateModel(
            name='subjectpapermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esubject', models.CharField(choices=[('Maths', 'Maths'), ('English', 'English'), ('English', 'Urdu')], max_length=50)),
                ('total_marks', models.IntegerField()),
                ('obtained_marks', models.IntegerField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.examsmodel')),
                ('pstudent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentmodel')),
            ],
        ),
        migrations.DeleteModel(
            name='examresultmodel',
        ),
    ]
