# Generated by Django 5.0 on 2023-12-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_rename_taken_by_examsmodel_studentforexam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsmodel',
            name='esubject',
            field=models.CharField(choices=[('Maths', 'Maths'), ('English', 'English'), ('English', 'Urdu')], default='English', max_length=50),
        ),
    ]
