# Generated by Django 5.0 on 2023-12-20 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_examsmodel_esubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsmodel',
            name='selected_class',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='2', max_length=50),
        ),
        migrations.AlterField(
            model_name='examsmodel',
            name='studentforexam',
            field=models.ManyToManyField(blank=True, to='student.studentmodel'),
        ),
    ]
