# Generated by Django 5.0 on 2023-12-21 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_studentmodel_user_studentmodel_user_type'),
    ]

    operations = [
        
    ]
