# Generated by Django 5.0 on 2023-12-27 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_studentmodel_user_studentmodel_user_type'),
    ]

    operations = [
        
    ]
