# Generated by Django 5.0 on 2023-12-27 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0014_remove_staffmodel_address_and_more'),
        ('student', '0013_remove_studentmodel_user'),
    ]

    operations = [
        
    ]
