# Generated by Django 5.0 on 2023-12-27 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_alter_studentmodel_admitted_by'),
    ]

    operations = [
       
    ]
