# Generated by Django 5.0 on 2023-12-27 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_remove_studentmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='admitted_by',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='user',
        ),
    ]
