# Generated by Django 5.0 on 2023-12-27 11:28

import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0015_remove_staffmodel_address_and_more'),
        ('student', '0017_remove_studentmodel_admitted_by_and_more'),
        ('useradmin', '0010_delete_roletype_alter_useradminmodel_options'),
    ]

    operations = [
       
    ]
