# Generated by Django 5.0 on 2023-12-27 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_alter_studentmodel_options_and_more'),
    ]

    operations = [
        
    ]
