# Generated by Django 5.0 on 2023-12-27 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0022_alter_studentmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsmodel',
            name='studentforexam',
            field=models.ManyToManyField(blank=True, to='student.studentmodel'),
        ),
        migrations.AddField(
            model_name='subjectpapermodel',
            name='pstudent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.studentmodel'),
            preserve_default=False,
        ),
    ]
