# Generated by Django 5.0 on 2023-12-28 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0020_alter_staffmodel_added_by'),
        ('student', '0023_examsmodel_studentforexam_subjectpapermodel_pstudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examsmodel',
            name='invigilator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staffmodel'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='admitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staffmodel'),
        ),
    ]
