# Generated by Django 5.0 on 2023-12-18 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useradmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradminmodel',
            name='im',
            field=models.ImageField(upload_to='useradmin'),
        ),
    ]
