# Generated by Django 5.0 on 2023-12-27 09:27

import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useradmin', '0004_customuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useradminmodel',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='useradminmodel',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='useradminmodel',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='useradminmodel',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='useradminmodel',
            name='id',
        ),
        migrations.RemoveField(
            model_name='useradminmodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='useradminmodel',
            name='role',
        ),
        migrations.AddField(
            model_name='useradminmodel',
            name='customuser_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='useradmin.customuser'),
            preserve_default=False,
        ),
    ]
