# Generated by Django 5.0 on 2023-12-27 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useradmin', '0005_alter_useradminmodel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useradminmodel',
            name='join_date',
        ),
    ]
