# Generated by Django 5.0 on 2023-12-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useradmin', '0006_remove_useradminmodel_join_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='useradminmodel',
            name='join_date',
            field=models.DateField(auto_now=True),
        ),
    ]
