# Generated by Django 5.0 on 2023-12-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useradmin', '0007_useradminmodel_join_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='useradminmodel',
            name='descrip',
            field=models.CharField(default=1, max_length=50, verbose_name='Description'),
            preserve_default=False,
        ),
    ]
