# Generated by Django 5.0 on 2023-12-27 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useradmin', '0009_alter_customuser_user_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoleType',
        ),
        migrations.AlterModelOptions(
            name='useradminmodel',
            options={'verbose_name': 'User-admin', 'verbose_name_plural': 'User-admins'},
        ),
    ]
