# Generated by Django 5.0 on 2023-12-28 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useradmin', '0014_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
