# Generated by Django 5.0 on 2024-01-04 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useradmin', '0015_alter_customuser_name'),
    ]

    operations = [
        
    ]
