# Generated by Django 4.1 on 2024-01-04 15:57

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useradmin', '0016_alter_useradminmodel_options_and_more'),
    ]

    operations = [
        
    ]
