# Generated by Django 5.0.1 on 2024-01-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useradmin', '0017_alter_useradminmodel_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useradminmodel',
            options={'verbose_name': 'User-teacher', 'verbose_name_plural': 'User-teachers'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
